# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Codeigniter4 indonesia | Tutorial 
description: > # this means to ignore newlines until "baseurl:"
  Install Codeignter4 tutorial di HP Kamu <a href="http://codeigniter4-id.github.io/unduh/1.apk">Download</a> for jekyll sites
baseurl: "https://codeigniter4-id.github.io/tutorial"
url: "https://codeigniter4-id.github.io/tutorial"
permalink: /:year/:month/:day/:title
repository: codeigniter4-id/tutorial
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/codeigniter4-id"
user: "Codeigniter4 Indonesia"
user_email: "fsteamcyber@gmail.com"
contact_url: "https://forms.gle/xzCDTgPmYwUjuQ566"
google_tracking_id: "G-QLX2F3MT8E"
google_site_verification: "G-QLX2F3MT8E"
disqus_shortname: "https-codeigniter4-id-github-io-tutorial"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
